/**
 * AI provider abstraction — PRD §7, §9.5, §11.2, §11.7.
 *
 * The SHAPE of this interface is the primary §9.5 control. What it deliberately
 * OMITS is the design:
 *
 *   - no database handle, no Model, no callback  -> a provider cannot retrieve
 *   - no AuthContext, no userId, no role         -> a provider cannot authorize
 *   - no subsidiaryId, documentId, chunkId       -> a provider cannot NAME a real
 *     resource, so a fabricated citation is not EXPRESSIBLE, not merely filtered
 *   - no filename, storage key, or env value     -> nothing about the deployment
 *
 * "The model must never be used as the authorization layer" (§9.5) is therefore
 * not a rule someone has to remember: there is no parameter through which a
 * provider could participate in an authorization decision, and no return field
 * the service writes anywhere privileged.
 *
 * §11.7 (may external providers process government documents?) is a BLOCKING
 * production decision. Only `local` exists — it answers offline from passages
 * this server already authorised, so no document leaves the machine.
 */

/** One already-authorised passage. `ref` is an opaque server-issued label, NOT an id. */
export interface RetrievedPassage {
  /** 'S1'..'Sn'. The only identifier the model ever sees. */
  ref: string;
  /** UNTRUSTED third-party document text. Escaped and fenced before any model sees it. */
  text: string;
  pageNumber?: number;
  section?: string;
}

export interface AnswerRequest {
  question: string;
  /** Already authorization-filtered. The provider does no retrieval of its own. */
  passages: RetrievedPassage[];
  style: 'standard' | 'parliamentary';
  maxAnswerChars: number;
  /**
   * Per-request delimiter nonce, generated by the SERVICE (not the adapter) so
   * the adapter stays deterministic and the neutralisation test can pin it.
   * A document author cannot forge a closing fence they cannot guess.
   */
  nonce: string;
}

export interface AnswerResult {
  /**
   * Sentences joined, each followed by a `{{ref:Sx}}` placeholder. The SERVICE
   * rewrites those to `[1]`, `[2]` after validation — the provider never emits
   * a final citation marker.
   */
  answerText: string;
  /**
   * Refs the provider CLAIMS to have used.
   *
   * Validated by the caller against the refs actually issued for THIS request
   * and discarded on mismatch (§9.5) — never trusted, never clamped into range.
   */
  citedRefs: string[];
  /** §9.5 "distinguish sourced facts from unsupported content" as a boolean, not a hedge. */
  unsupported: boolean;
  providerName: string;
  model?: string;
  latencyMs: number;
}

export interface AiProvider {
  readonly name: string;
  readonly promptVersion: string;
  answer(req: AnswerRequest): Promise<AnswerResult>;
}

/**
 * The refusal string is a SOURCE-CODE CONSTANT, so document content can never
 * manipulate what a refusal says — which matters, because a refusal is exactly
 * what an attacker would want replaced with a fabricated answer.
 */
export const UNSUPPORTED_ANSWER =
  'The authorised source material available to you does not contain enough information to answer this question.';
